import {test,expect,Page} from '@playwright/test'
import {mkdirSync} from 'node:fs'
const baseURL=process.env.CONNECT_URL||'http://localhost:18080'
const unique=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,6)
async function register(page:Page,name:string,id:string){
 await page.goto('/')
 await page.getByRole('button',{name:'Создать аккаунт',exact:true}).click()
 await page.getByLabel('Как вас зовут').fill(name)
 await page.getByLabel('Имя пользователя').fill('user_'+id)
 await page.getByLabel('Электронная почта').fill(id+'@example.com')
 await page.getByLabel('Пароль',{exact:true}).fill('Connect_test_2026!')
 await page.locator('form').getByRole('button',{name:'Создать аккаунт'}).click()
 await expect(page.locator('.connection')).toHaveText('На связи')
 await expect(page.locator('.page-heading h1')).toContainText(name.split(' ')[0])
}
test('two accounts: friends, chat, read receipts, video and audio calls',async({browser})=>{
 const first=await browser.newContext({baseURL,permissions:['camera','microphone'],viewport:{width:1440,height:1000}})
 const second=await browser.newContext({baseURL,permissions:['camera','microphone'],viewport:{width:1280,height:900}})
 const alice=await first.newPage(),bob=await second.newPage(),tag=unique(),aliceName='Алиса '+tag,bobName='Борис '+tag
 const errors:string[]=[]
 alice.on('pageerror',e=>errors.push(e.message));bob.on('pageerror',e=>errors.push(e.message))
 await register(alice,aliceName,'a'+tag);await register(bob,bobName,'b'+tag)
 mkdirSync('test-results/visual',{recursive:true})
 await alice.screenshot({path:'test-results/visual/home-desktop.png',fullPage:true})
 await alice.locator('.welcome-card').getByRole('button',{name:'Найти друзей'}).click()
 await alice.getByLabel('Поиск по имени').fill(bobName)
 const person=alice.locator('.person-card').filter({hasText:bobName})
 await person.getByRole('button',{name:'Добавить',exact:true}).click()
 await expect(person).toContainText('Заявка отправлена')
 await bob.getByRole('button',{name:'Заявки в друзья',exact:true}).click()
 await bob.getByRole('button',{name:'Принять',exact:true}).click({timeout:25000})
 await expect(bob.getByRole('status')).toContainText('Теперь вы друзья')
 await person.getByRole('button',{name:'Написать',exact:true}).click()
 await alice.getByRole('textbox',{name:'Сообщение',exact:true}).fill('Привет! Проверяем настоящий чат 💙')
 await alice.getByRole('button',{name:'Отправить сообщение'}).click()
 await bob.locator('.sidebar').getByRole('button',{name:/^Чаты/}).click()
 await expect(bob.locator('.chat-row').filter({hasText:aliceName})).toBeVisible({timeout:25000})
 await bob.locator('.chat-row').filter({hasText:aliceName}).first().click()
 await expect(bob.locator('.message-bubble')).toContainText('Проверяем настоящий чат')
 await expect(alice.getByLabel('Прочитано')).toBeVisible()
 await bob.getByRole('textbox',{name:'Сообщение',exact:true}).fill('Сообщение получено. Давай созвонимся!')
 await bob.getByRole('button',{name:'Отправить сообщение'}).click()
 await expect(alice.locator('.message-bubble').last()).toContainText('Давай созвонимся')
 await alice.screenshot({path:'test-results/visual/chat-desktop.png',fullPage:true})
 for(const kind of ['Видеозвонок','Аудиозвонок']){
  await alice.getByRole('button',{name:kind,exact:true}).click()
  await expect(bob.getByRole('dialog',{name:'Звонок'})).toBeVisible()
  await bob.getByRole('button',{name:'Принять звонок'}).click()
  await expect(alice.locator('.call-person p')).toHaveText(/\d{2}:\d{2}/,{timeout:30000})
  await expect(bob.locator('.call-person p')).toHaveText(/\d{2}:\d{2}/,{timeout:30000})
  const remote=kind==='Видеозвонок'?'.remote-video':'.audio-stream'
  await expect.poll(()=>bob.locator(remote).evaluate((el:HTMLVideoElement)=>({ready:el.readyState,tracks:(el.srcObject as MediaStream)?.getTracks().map(t=>t.readyState)}))).toMatchObject({ready:4})
  if(kind==='Видеозвонок')await bob.screenshot({path:'test-results/visual/video-call.png',fullPage:true})
  await alice.getByRole('button',{name:'Выключить микрофон'}).click()
  await expect(alice.getByRole('button',{name:'Включить микрофон'})).toBeVisible()
  await bob.getByRole('button',{name:'Завершить звонок'}).click()
  await expect(alice.getByRole('dialog',{name:'Звонок'})).not.toBeVisible()
 }
 await alice.getByRole('button',{name:'Видеозвонок',exact:true}).click()
 await bob.getByRole('button',{name:'Отклонить звонок'}).click()
 await expect(alice.getByRole('dialog',{name:'Звонок'})).not.toBeVisible()
 expect(errors).toEqual([])
 await first.close();await second.close()
})
test('mobile layout, registration and profile',async({browser})=>{
 const context=await browser.newContext({baseURL,viewport:{width:390,height:844},isMobile:true,hasTouch:true,permissions:['camera','microphone']})
 const page=await context.newPage(),tag=unique()
 await page.goto('/')
 await page.screenshot({path:'test-results/visual/auth-mobile.png',fullPage:true})
 await register(page,'Марина '+tag,'m'+tag)
 await page.screenshot({path:'test-results/visual/home-mobile.png',fullPage:true})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()
 await page.locator('.bottom-nav').getByRole('button',{name:'Профиль',exact:true}).click()
 await page.getByLabel('О себе').fill('Люблю путешествия и хорошую компанию')
 await page.getByRole('button',{name:'Сохранить изменения'}).click()
 await expect(page.getByRole('status')).toContainText('Профиль обновлён')
 await page.reload()
 await page.locator('.bottom-nav').getByRole('button',{name:'Профиль',exact:true}).click()
 await expect(page.getByLabel('О себе')).toHaveValue('Люблю путешествия и хорошую компанию')
 await context.close()
})
