import {useEffect,useRef,useState} from 'react'
import {ArrowRight,Heart,MessageCircle,Phone,ShieldCheck,Eye,EyeOff,LoaderCircle} from 'lucide-react'
import {api,initials,setToken} from './api'
export function Avatar({name,size='',url,id=0}:{name:string;size?:string;url?:string|null;id?:number}){return <span className={`avatar ${size} color-${id%5}`}>{url&&/^https?:\/\//.test(url)?<img src={url} alt={name} onError={e=>{e.currentTarget.style.display='none'}}/>:initials(name)}</span>}
export function Empty({icon:Icon=MessageCircle,title,text,action,label}:{icon?:typeof MessageCircle;title:string;text:string;action?:()=>void;label?:string}){return <div className="empty"><span className="empty-icon"><Icon size={30}/></span><h3>{title}</h3><p>{text}</p>{action&&<button className="primary" onClick={action}>{label}<ArrowRight size={17}/></button>}</div>}
export function Media({stream,muted=false,className=''}:{stream:MediaStream|null;muted?:boolean;className?:string}){const ref=useRef<HTMLVideoElement>(null);useEffect(()=>{if(ref.current){ref.current.srcObject=stream;void ref.current.play().catch(()=>{})}},[stream]);return <video ref={ref} autoPlay playsInline muted={muted} className={className}/>}
export function CallTimer({started}:{started:number}){const[now,setNow]=useState(Date.now());useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[]);const s=Math.max(0,Math.floor((now-started)/1000));return <span>{Math.floor(s/60).toString().padStart(2,'0')}:{(s%60).toString().padStart(2,'0')}</span>}
export function Auth({onDone,notify}:{onDone:(token:string)=>void;notify:(s:string)=>void}){
 const[signup,setSignup]=useState(false),[busy,setBusy]=useState(false),[show,setShow]=useState(false),[error,setError]=useState('')
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const data=new FormData(e.currentTarget),email=String(data.get('email')),password=String(data.get('password'));try{if(signup)await api('/auth/register','POST',{email,password,username:String(data.get('username'))});const result=await api<{access_token:string}>('/auth/login','POST',{email,password});setToken(result.access_token);if(signup){try{await api('/users/profile','POST',{display_name:String(data.get('name'))})}catch{notify('Аккаунт создан. Имя можно изменить в профиле.')}}onDone(result.access_token)}catch(err){setError((err as Error).message)}finally{setBusy(false)}}
 return <div className="auth-layout"><section className="auth-story"><a className="brand" href="/"><img src="/icon.svg" alt=""/>Connect<span className="beta">BETA</span></a><div className="auth-copy"><span className="eyebrow">БЛИЖЕ, ДАЖЕ НА РАССТОЯНИИ</span><h1>Ваши люди.<br/>Ваши разговоры.<br/><span>Ваш Connect.</span></h1><p>Делитесь маленькими радостями,<br/>стройте большие планы. Просто будьте рядом.</p><div className="conversation-art" aria-hidden="true"><span className="orb orb-one"/><span className="orb orb-two"/><div className="art-message"><span className="art-avatar">М</span><div><b>Есть минутка?</b><span>Хочу рассказать кое-что хорошее ✨</span></div><span className="art-time">сейчас</span></div><div className="art-reply">Для тебя — всегда <Heart size={17}/></div><div className="art-call"><span><Phone size={22}/></span><div><b>На одной волне</b><small>Голосом. По видео. Как вам ближе.</small></div><i/></div></div></div><div className="auth-foot"><ShieldCheck size={18}/> Личные разговоры — только для участников</div></section><section className="auth-form-panel"><div className="auth-form-wrap"><div className="mobile-brand"><img src="/icon.svg" alt=""/>Connect</div><span className="eyebrow">РАДЫ ВАС ВИДЕТЬ</span><h2>{signup?'Начнём знакомство':'С возвращением'}</h2><p>{signup?'Создайте свой уголок общения.':'Ваши друзья уже где-то рядом.'}</p><div className="segmented"><button className={!signup?'selected':''} onClick={()=>{setSignup(false);setError('')}}>Войти</button><button className={signup?'selected':''} onClick={()=>{setSignup(true);setError('')}}>Создать аккаунт</button></div><form onSubmit={submit}>{signup&&<><label>Как вас зовут<input name="name" placeholder="Имя и фамилия" required minLength={2} maxLength={100} autoComplete="name"/></label><label>Ник пользователя<input name="username" placeholder="Например, marina" pattern="[A-Za-z0-9_]{3,50}" title="От 3 до 50 символов: латинские буквы, цифры и подчёркивание" required minLength={3} maxLength={50} autoComplete="username"/></label></>}<label>Электронная почта<input name="email" type="email" placeholder="you@example.com" autoComplete="email" required/></label><label>Пароль<div className="password-input"><input name="password" type={show?'text':'password'} placeholder="Не менее 8 символов" minLength={8} maxLength={128} required autoComplete={signup?'new-password':'current-password'}/><button type="button" className="icon-button" aria-label={show?'Скрыть пароль':'Показать пароль'} onClick={()=>setShow(!show)}>{show?<EyeOff size={19}/>:<Eye size={19}/>}</button></div></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="primary auth-submit" disabled={busy}>{busy?<LoaderCircle className="spin" size={20}/>:<>{signup?'Создать аккаунт':'Войти в Connect'}<ArrowRight size={19}/></>}</button></form><div className="auth-note"><MessageCircle size={18}/><span>Больше, чем общение.<br/><b>Место, где вас ждут.</b></span></div></div></section></div>
}
