import {createRoot} from 'react-dom/client'
import {ArrowUpRight,Bell,Heart,Home,LoaderCircle,MessageCircle,Mic,MicOff,Phone,PhoneOff,Search,Settings,ShieldCheck,User,Users,Video,VideoOff,WifiOff,X} from 'lucide-react'
import {Auth,Avatar,CallTimer,Media} from './components'
import {Dashboard} from './Dashboard'
import {Messenger} from './Messenger'
import {Friends,Calls,ProfilePage} from './Pages'
import {Page,useConnect} from './useConnect'
import './styles.css'
const navigation:[Page,typeof Home,string][]=[['home',Home,'Главная'],['chats',MessageCircle,'Чаты'],['friends',Users,'Друзья'],['calls',Phone,'Звонки'],['profile',User,'Профиль']]
function App(){const a=useConnect(),rtc=a.rtc
 const toast=a.toast&&<div role="status" className="toast">{a.toast}<button aria-label="Закрыть уведомление" onClick={()=>a.setToast('')}><X size={16}/></button></div>
 if(!a.token)return <><Auth onDone={a.changeToken} notify={a.notify}/>{toast}</>
 if(a.loading||(!a.account&&!a.startupError))return <div className="loading-screen"><img src="/icon.svg" alt="Connect"/><LoaderCircle className="spin"/><p>Собираем ваши разговоры…</p></div>
 if(a.startupError)return <div className="loading-screen"><WifiOff size={38}/><h2>Не удалось подключиться</h2><p>{a.startupError}</p><button className="primary" onClick={()=>void a.initialize()}>Попробовать снова</button><button className="text-button" onClick={a.logout}>Выйти</button></div>
 return <div className={`app-shell ${a.page==='chats'?'chat-page':''} ${a.activeChat?'conversation-open':''}`}><aside className="sidebar"><button className="brand" onClick={()=>a.go('home')}><img src="/icon.svg" alt=""/>Connect</button><span className="sidebar-caption">ВАШЕ ПРОСТРАНСТВО</span><nav>{navigation.map(([key,Icon,label])=><button key={key} className={a.page===key?'nav-item active':'nav-item'} onClick={()=>a.go(key)}><Icon size={21}/><span>{label}</span>{key==='chats'&&a.unread>0&&<b className="badge">{a.unread}</b>}{key==='friends'&&a.incoming.length>0&&<b className="badge">{a.incoming.length}</b>}</button>)}</nav><div className="sidebar-card"><span className="little-heart"><Heart size={21}/></span><h4>Ближе друг к другу</h4><p>Иногда одно «привет»<br/>меняет целый день.</p><button className="text-button" onClick={a.findPeople}>Найти своих <ArrowUpRight size={16}/></button></div><button className="sidebar-profile" onClick={()=>a.go('profile')}><Avatar name={a.name} id={a.account!.id} size="small"/><span><b>{a.name}</b><small>Мой профиль</small></span><Settings size={18}/></button></aside><div className="workspace"><header className="topbar"><button className="mobile-brand" onClick={()=>a.go('home')}>Connect<span className="brand-dot"/></button><div className="top-search"><Search size={19}/><input placeholder="Найти человека по @нику" aria-label="Поиск людей" value={a.query} onFocus={()=>{a.go('friends');a.setFriendTab('search')}} onChange={e=>a.setQuery(e.target.value)}/><span className="search-key">⌕</span></div><div className="top-actions"><span className={`connection ${a.connected?'online':''}`}><i/>{a.connected?'На связи':'Подключаемся'}</span><button className="icon-button notification-button" aria-label="Заявки в друзья" onClick={()=>{a.go('friends');a.setFriendTab('requests')}}><Bell size={22}/>{a.incoming.length>0&&<span className="notification-dot"/>}</button><button className="profile-button" aria-label="Мой профиль" onClick={()=>a.go('profile')}><Avatar name={a.name} id={a.account!.id} size="small" url={a.profile?.avatar_url}/></button></div></header><main>{a.page==='home'&&<Dashboard app={a}/>} {a.page==='chats'&&<Messenger app={a}/>} {a.page==='friends'&&<Friends app={a}/>} {a.page==='calls'&&<Calls app={a}/>} {a.page==='profile'&&<ProfilePage app={a}/>}</main></div><nav className="bottom-nav">{navigation.map(([key,Icon,label])=><button key={key} className={a.page===key?'active':''} onClick={()=>a.go(key)}><span><Icon size={23}/>{key==='chats'&&a.unread>0&&<b>{a.unread}</b>}</span>{label}</button>)}</nav>{toast}
 {rtc.call&&<div className="call-backdrop"><section className={`call-window ${rtc.call.media==='video'&&rtc.remote?'with-video':''}`} role="dialog" aria-label="Звонок"><div className="call-window-top"><span><img src="/icon.svg" alt=""/>Connect</span><span className="call-secure"><ShieldCheck size={15}/> Личный звонок</span></div>{rtc.remote&&<Media stream={rtc.remote} className={rtc.call.media==='video'?'remote-video':'audio-stream'}/>}<div className="call-person"><Avatar name={rtc.call.name} id={rtc.call.targetId} size="call-avatar"/><h2>{rtc.call.name}</h2><p>{rtc.call.phase==='incoming'?`Входящий ${rtc.call.media==='video'?'видеозвонок':'аудиозвонок'}`:rtc.call.phase==='active'?<CallTimer started={rtc.call.started!}/>:rtc.call.phase==='outgoing'?'Вызываем…':'Соединяем…'}</p></div>{rtc.local&&rtc.call.media==='video'&&<Media stream={rtc.local} muted className="local-video"/>}<div className="call-controls">{rtc.call.phase==='incoming'?<><button className="call-control decline" aria-label="Отклонить звонок" onClick={()=>rtc.hangup('declined')}><PhoneOff/><span>Отклонить</span></button><button className="call-control accept" aria-label="Принять звонок" onClick={()=>void rtc.accept()}><Phone/><span>Принять</span></button></>:<><button className={`call-control ${rtc.muted?'toggled':''}`} aria-label={rtc.muted?'Включить микрофон':'Выключить микрофон'} onClick={rtc.toggleMic}>{rtc.muted?<MicOff/>:<Mic/>}<span>Микрофон</span></button>{rtc.call.media==='video'&&<button className={`call-control ${rtc.cameraOff?'toggled':''}`} aria-label="Переключить камеру" onClick={rtc.toggleCamera}>{rtc.cameraOff?<VideoOff/>:<Video/>}<span>Камера</span></button>}<button className="call-control decline" aria-label="Завершить звонок" onClick={()=>{rtc.hangup();void a.refresh().catch(()=>{})}}><PhoneOff/><span>Завершить</span></button></>}</div></section></div>}</div>
}
createRoot(document.getElementById('root')!).render(<App/> )
